### ISSUE TITLE
Question about docker compose stop_infra

### ISSUE THREAD

**Issue by azdanov** [sivaprasadreddy/spring-boot-microservices-course#3]
In the `Taskfile.yml` I saw that the stop task is written in this way:
https://github.com/sivaprasadreddy/spring-boot-microservices-course/blob/bf938a40bb817828547a47b9c27e701a61deae27/Taskfile.yml#L32-L35

Is there any reason not to use `docker compose down`?

I did some research and only difference was that `rm -f` doesn't remove the created network, while `down` does.

**Comment by sivaprasadreddy** [comment]
The same network is shared by infra and apps. So, I am just removing the containers leaving the network to continue.

**Comment by azdanov** [comment]
Oh, I didn't know about the network being shared. Good point.

**Comment by azdanov** [comment]
I've experimented a bit by using compose profiles: https://docs.docker.com/compose/profiles/

It might be a good approach too. What do you think?

https://github.com/azdanov/bookstore/blob/e4cf6edc48685e1ce287f105ad64b30f074c660a/deployment/compose.yml#L6-L7

https://github.com/azdanov/bookstore/blob/e4cf6edc48685e1ce287f105ad64b30f074c660a/deployment/compose.yml#L26-L27

https://github.com/azdanov/bookstore/blob/e4cf6edc48685e1ce287f105ad64b30f074c660a/Taskfile.yml#L31-L37
