### ISSUE TITLE
Message required in OrderItem record

### ISSUE THREAD

**Issue by sakthiece08** [sivaprasadreddy/spring-boot-microservices-course#8]
Hi @sivaprasadreddy 
Message attribute to be defined for @NotNull and @Min annotation in OrderItem record to display the validation message properly in the error response for Quantity field.

> @NotNull(message = "Quantity is required") @Min(value = 1, message = "Min quantity must be 1") Integer quantity

> source file path: 
order-service/src/main/java/com/sivalabs/bookstore/orders/domain/models/**OrderItem.java**

**Comment by sivaprasadreddy** [comment]
Done
